"use client";
import {useEffect,useMemo,useState} from "react";
import {Lead,Message,Stage} from "../lib/types";
import {LayoutDashboard,Users,MessageSquare,Settings,Search,Plus,ArrowUpRight,Bot,ShieldCheck,Send,UserRoundCheck,Activity} from "lucide-react";

const stages:Stage[]=["new","contacted","qualified","handoff","won","lost"];
const stageLabel:Record<Stage,string>={new:"Nouveau",contacted:"Contacté",qualified:"Qualifié",handoff:"Handoff",won:"Gagné",lost:"Perdu"};

export default function Home(){
 const [section,setSection]=useState("overview");
 const [leads,setLeads]=useState<Lead[]>([]);
 const [selected,setSelected]=useState<Lead | null>(null);
 const [messages,setMessages]=useState<Message[]>([]);
 const [query,setQuery]=useState("");
 const [toast,setToast]=useState(""); const [aiBusy,setAiBusy]=useState(false);
 const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(""),2400)};
 useEffect(()=>{(async()=>{try{const r=await fetch("/api/leads");const d=await r.json();if(r.ok&&Array.isArray(d.leads)){setLeads(d.leads);if(d.leads[0])setSelected(d.leads[0]);}}catch{}})()},[]);
 useEffect(()=>{if(!selected?.id)return;(async()=>{try{const r=await fetch("/api/messages?leadId="+encodeURIComponent(selected.id));const d=await r.json();if(r.ok&&Array.isArray(d.messages))setMessages(d.messages);}catch{}})()},[selected?.id]);
 const filtered=useMemo(()=>leads.filter(l=>(l.company+" "+l.contact+" "+l.need).toLowerCase().includes(query.toLowerCase())),[leads,query]);
 const stats={all:leads.length,qualified:leads.filter(x=>x.stage==="qualified"||x.stage==="handoff").length,handoff:leads.filter(x=>x.stage==="handoff").length,score:leads.length?Math.round(leads.reduce((a,x)=>a+x.score,0)/leads.length):0};
 const addLead=async()=>{try{const r=await fetch("/api/leads",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({company:"Nouveau prospect",contact:"Contact",role:"Décideur",channel:"manual",need:"À découvrir",budget:"À définir",stage:"new",score:50})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Erreur");const l:Lead={id:d.id,company:"Nouveau prospect",contact:"Contact",role:"Décideur",channel:"manual",need:"À découvrir",budget:"À définir",stage:"new",score:50,lastMessage:"",createdAt:new Date().toISOString()};setLeads([l,...leads]);setSelected(l);setSection("leads");notify("Prospect créé dans Supabase")}catch(e){notify(e instanceof Error?e.message:"Erreur")}};
 const updateStage=async(stage:Stage)=>{if(!selected)return;try{const r=await fetch("/api/leads",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:selected.id,stage})});if(!r.ok)throw new Error("Impossible de mettre à jour le statut");setLeads(leads.map(l=>l.id===selected.id?{...l,stage}:l));setSelected({...selected,stage});notify("Statut mis à jour")}catch(e){notify(e instanceof Error?e.message:"Erreur")}};
 const send=(text:string)=>{if(!selected||!text.trim())return;setMessages([...messages,{id:Date.now().toString(),leadId:selected.id,sender:"human",text,at:new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}]);notify("Message ajouté à la conversation")};
 const aiReply=async()=>{setAiBusy(true);try{const history=messages.filter(m=>m.leadId===selected.id).map(m=>({role:m.sender==="lead"?"user":"assistant",content:m.text}));const r=await fetch("/api/ai/chat",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({leadId:selected.id,messages:history})});const d=await r.json();if(!r.ok)throw new Error(d.error||"AI error");setMessages([...messages,{id:Date.now().toString(),leadId:selected.id,sender:"ai",text:d.text,at:new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}]);notify("AI response generated")}catch(e){notify(e instanceof Error?e.message:"AI error")}finally{setAiBusy(false)}};

 return <div className="app">
  <aside className="sidebar"><div className="brand">miobzou<span>·</span></div><div className="nav">
   <button className={section==="overview"?"active":""} onClick={()=>setSection("overview")}><LayoutDashboard size={16}/> Overview</button>
   <button className={section==="leads"?"active":""} onClick={()=>setSection("leads")}><Users size={16}/> Prospects</button>
   <button className={section==="inbox"?"active":""} onClick={()=>setSection("inbox")}><MessageSquare size={16}/> Conversations</button>
   <button className={section==="settings"?"active":""} onClick={()=>setSection("settings")}><Settings size={16}/> Settings</button>
  </div><div style={{position:"absolute",bottom:22,left:16,right:16}} className="card"><div style={{display:"flex",gap:8,alignItems:"center"}}><ShieldCheck size={16}/><span style={{fontSize:12}}>Human control enabled</span></div><div className="muted" style={{fontSize:11,marginTop:6}}>AI stops before payment.</div></div></aside>
  <main className="main">
   <div className="top"><div><div className="eyebrow">Revenue operating system</div><div className="title">{section==="overview"?"Command Center":section==="leads"?"Prospects":section==="inbox"?"AI Inbox":"System Settings"}</div><div className="muted">Prospecting → qualification → human handoff</div></div><div className="actions"><input className="search" placeholder="Search prospects..." value={query} onChange={e=>setQuery(e.target.value)}/><button className="btn primary" onClick={addLead}><Plus size={15}/> New lead</button></div></div>

   {section==="overview"&&<><div className="grid">
    <Metric label="Total prospects" value={stats.all} icon={<Users size={17}/>}/>
    <Metric label="Qualified" value={stats.qualified} icon={<UserRoundCheck size={17}/>}/>
    <Metric label="Human handoff" value={stats.handoff} icon={<ArrowUpRight size={17}/>}/>
    <Metric label="Avg. intent score" value={stats.score+"/100"} icon={<Activity size={17}/>}/>
   </div><div className="layout"><div className="card"><div className="sectionTitle">Pipeline</div><table className="table"><thead><tr><th>Prospect</th><th>Need</th><th>Intent</th><th>Stage</th></tr></thead><tbody>{filtered.map(l=><tr key={l.id} onClick={()=>{setSelected(l);setSection("inbox")}} style={{cursor:"pointer"}}><td><b>{l.company}</b><div className="muted">{l.contact} · {l.channel}</div></td><td>{l.need}</td><td><span className={"pill "+(l.score>85?"hot":"blue")}>{l.score}</span></td><td><span className={"pill "+(l.stage==="handoff"?"green":"")}>{stageLabel[l.stage]}</span></td></tr>)}</tbody></table></div><div className="card"><div className="sectionTitle">AI activity</div><div style={{display:"grid",gap:16}}><ActivityItem title="Lead qualified" text="Atlas Habitat crossed the handoff threshold." time="2m"/><ActivityItem title="Intent detected" text="Casa Market mentioned online payments." time="19m"/><ActivityItem title="Follow-up ready" text="Noura Studio asked for details." time="1h"/></div></div></div></>}

   {section==="leads"&&<div className="card"><div className="sectionTitle">Lead database <span className="muted">({filtered.length})</span></div><table className="table"><thead><tr><th>ID</th><th>Company</th><th>Channel</th><th>Need</th><th>Budget</th><th>Score</th><th>Stage</th></tr></thead><tbody>{filtered.map(l=><tr key={l.id}><td>{l.id}</td><td><b>{l.company}</b><div className="muted">{l.contact} · {l.role}</div></td><td>{l.channel}</td><td>{l.need}</td><td>{l.budget}</td><td><span className="pill blue">{l.score}</span></td><td><select value={l.stage} onChange={e=>{setSelected(l);updateStage(e.target.value as Stage)}} style={{background:"#10151d",color:"white",border:"1px solid #27303d",padding:"6px",borderRadius:7}}>{stages.map(s=><option key={s} value={s}>{stageLabel[s]}</option>)}</select></td></tr>)}</tbody></table></div>}

   {section==="inbox"&&<div className="layout"><div className="card chat"><div className="sectionTitle" style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><span><Bot size={16}/> AI conversation · {selected.company}</span><button className="btn" onClick={aiReply} disabled={aiBusy}>{aiBusy?"Generating…":"Generate AI reply"}</button></div><div className="messages">{messages.filter(m=>m.leadId===selected.id).map(m=><div key={m.id} className={"msg "+(m.sender==="lead"?"lead":"ai")}><b>{m.sender==="lead"?selected.contact:m.sender==="human"?"You":"AI"}</b><br/>{m.text}<div className="muted" style={{fontSize:10,marginTop:4}}>{m.at}</div></div>)}</div><div className="composer"><input id="composer" placeholder="Write a human message..." onKeyDown={e=>{if(e.key==="Enter"){send(e.currentTarget.value);e.currentTarget.value=""}}}/><button className="btn primary" onClick={()=>{const el=document.getElementById("composer") as HTMLInputElement;send(el.value);el.value=""}}><Send size={15}/></button></div></div><div className="card"><div className="sectionTitle">Lead intelligence</div><div className="field"><label>Need</label><input value={selected.need} readOnly/></div><div className="two"><div className="field"><label>Intent score</label><input value={selected.score+"/100"} readOnly/></div><div className="field"><label>Budget</label><input value={selected.budget} readOnly/></div></div><div className="field"><label>Pipeline stage</label><select value={selected.stage} onChange={e=>updateStage(e.target.value as Stage)}>{stages.map(s=><option key={s} value={s}>{stageLabel[s]}</option>)}</select></div><button className="btn primary" style={{width:"100%"}} onClick={()=>updateStage("handoff")}><UserRoundCheck size={15}/> Request human handoff</button><div className="muted" style={{fontSize:11,marginTop:10}}>Handoff is the hard boundary before pricing/payment.</div></div></div>}

   {section==="settings"&&<div className="layout"><div className="card"><div className="sectionTitle">AI provider</div><div className="field"><label>Provider</label><select defaultValue="openai"><option value="openai">OpenAI</option><option value="anthropic">Anthropic</option><option value="custom">Custom webhook</option></select></div><div className="field"><label>API key</label><input type="password" placeholder="Stored server-side in production"/></div><div className="field"><label>Model</label><input defaultValue="gpt-5.6"/></div><button className="btn primary" onClick={()=>notify("Configuration saved locally")}>Save configuration</button></div><div className="card"><div className="sectionTitle">Autonomy policy</div><p className="muted">The agent can research, personalize outreach, qualify needs, handle ordinary objections and schedule a handoff.</p><p className="success">✓ No fabricated claims</p><p className="success">✓ No hidden impersonation</p><p className="success">✓ Stop before payment / contract</p><p className="success">✓ Full activity trail</p></div></div>}
  </main>{toast&&<div className="toast">{toast}</div>}
 </div>
}
function Metric({label,value,icon}:{label:string,value:string|number,icon:React.ReactNode}){return <div className="card"><div className="muted" style={{display:"flex",gap:7,alignItems:"center"}}>{icon}{label}</div><div className="metric">{value}</div><div className="success" style={{fontSize:11}}>Live workspace</div></div>}
function ActivityItem({title,text,time}:{title:string,text:string,time:string}){return <div style={{display:"flex",gap:10}}><div style={{width:8,height:8,borderRadius:99,background:"#7c9cff",marginTop:6}}/><div><b style={{fontSize:13}}>{title}</b><div className="muted" style={{fontSize:12,marginTop:3}}>{text}</div><div className="muted" style={{fontSize:10,marginTop:3}}>{time} ago</div></div></div>}
